import json
import subprocess

def run_scripts():
    # Run each individual script (assumed to be in the same directory)
    subprocess.run(['python', 'new_properties.py'])  # Script to extract property URLs
    subprocess.run(['python', 'property_page.py'])  # Script to extract Trakheesi URLs
    subprocess.run(['python', 'trakisee_prop_info.py'])  # Script to gather detailed property information

def combine_data():
    # Load data from the JSON files generated by individual scripts
    with open('json_files/property_urls.json', 'r') as f:
        property_urls = json.load(f)  # Original property URLs
        
    with open('json_files/properties_info.json', 'r') as f:
        properties_info = json.load(f)  # Contains Trakheesi URL, Bedrooms, and Bathrooms
    
    with open('json_files/tracksi_info.json', 'r') as f:
        trakheesi_info = json.load(f)  # Contains Property Value and Size

    # Combine the data as needed
    combined_info = []
    for i, property_data in enumerate(properties_info):
        # Ensure we don't go out of bounds for all lists
        if i < len(trakheesi_info) and i < len(property_urls):
            # Extract details from properties_info
            trakheesi_url = property_data['Trakheesi URL']
            bedrooms = property_data['Bedrooms']
            bathrooms = property_data['Bathrooms']

            # Extract details from trakheesi_info
            property_value = trakheesi_info[i].get('Property Value (AED)', 'N/A')  # Default to 'N/A' if not found
            property_size = trakheesi_info[i].get('Property Size (Sqm)', 'N/A')  # Default to 'N/A' if not found
            
            # Construct the combined dictionary
            combined_data = {
                'Original Property URL': property_urls[i],
                'Trakheesi URL': trakheesi_url,
                'Bedrooms': bedrooms,
                'Bathrooms': bathrooms,
                'Property Value (AED)': property_value,
                'Property Size (Sqm)': property_size
            }
            combined_info.append(combined_data)

    # Save the combined data to a new JSON file
    with open('json_files/final_property_info.json', 'w') as f:
        json.dump(combined_info, f, indent=4)

    print(f"Combined data saved to 'final_property_info.json' with {len(combined_info)} entries.")


def main():
    run_scripts()  # Execute all the individual scripts
    combine_data()  # Combine the results into one final JSON

if __name__ == "__main__":
    main()

