import json
import subprocess

def run_scripts():
    # Run each individual script (assumed to be in the same directory)
    subprocess.run(['python', 'script1.py'])  # Script to extract property URLs
    subprocess.run(['python', 'script2.py'])  # Script to extract Trakheesi URLs
    subprocess.run(['python', 'script3.py'])  # Script to gather detailed property information

def combine_data():
    # Load data from the JSON files generated by individual scripts
    with open('properties_info.json', 'r') as f:
        properties_info = json.load(f)
    
    with open('trakheesi_urls.json', 'r') as f:
        trakheesi_urls = json.load(f)

    # Combine the data as needed
    combined_info = []
    for i, property_data in enumerate(properties_info):
        if i < len(trakheesi_urls):  # Ensure we don't go out of bounds
            property_data['Trakheesi URL'] = trakheesi_urls[i]
            combined_info.append(property_data)

    # Save the combined data to a new JSON file
    with open('final_property_info.json', 'w') as f:
        json.dump(combined_info, f, indent=4)

def main():
    run_scripts()  # Execute all the individual scripts
    combine_data()  # Combine the results into one final JSON

if __name__ == "__main__":
    main()
